name: Tests

on:
  push:
    branches:
      -  main
      -  develop
  pull_request:
    branches:
      -  main
      -  develop
env:
  GOPROXY: direct
  
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GOFLAGS: -mod=vendor
      GOPROXY: "off"

    steps:

      - name: Set up Go 1.146
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.2'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
               
      - name: tidy
        run: make tidy

      - name: vendor
        run: make goVendor

      - name: Vet
        run: make vet

      - name: Test
        run: make test

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: build --rm-dist --snapshot
